rest_oai_pmh.settings:
  type: config_object
  label: 'Rest oai pmh settings'
  mapping:
    rest_oai_pmh:
      type: sequence
      label: 'Rest oai pmh'
      sequence:
        type: string
        label: 'Entity type'
